FROM arm32v7/ubuntu:xenial
MAINTAINER Leonardo Loures <luvres@hotmail.com>

# sudo apt-get install qemu-user-static binfmt-support
# sudo update-binfmts --enable qemu-arm
# sudo update-binfmts --display qemu-arm 
# cp /usr/bin/qemu-arm-static .
COPY qemu-arm-static /usr/bin/qemu-arm-static

## References
# https://matchboxdorry.gitbooks.io/matchboxblog/content/blogs/build_and_run_arm_images.html
# https://github.com/dashaub/ARM-RStudio/blob/master/ARM-RStudio.sh

RUN \
  # This script installs R and builds RStudio Desktop for ARM Chromebooks running Ubuntu 16.04
#	set -euo pipefail 
  \
  # Install R
	apt-get update \
	&& apt-get install -y \
		r-base \
		r-base-dev \
		wget \
		openjdk-8-jdk \
		checkinstall 
RUN \
  # Download RStudio source
  # Set RStudio version
	VERS='v1.1.447' \
	&& cd /tmp \
	&& wget "https://github.com/rstudio/rstudio/tarball/${VERS}" \
	&& mkdir "rstudio-$VERS" \
	&& tar xf "${VERS}" -C "rstudio-${VERS}" --strip-components 1 \
	&& rm "${VERS}" \
  \
  # Install dependencies
	&& cd rstudio-$VERS/dependencies/linux \
	&& sed -i 's/sudo//' ./install-dependencies-debian \
	&& sed -i 's/sudo//' ../common/install-boost \
	&& ./install-dependencies-debian 
#  \
#  # Configure cmake and build RStudio
#	&& cd "/tmp/rstudio-$VERS/" \
#	&& mkdir build \
#	&& cd build \
#	&& cmake .. \
#			-DRSTUDIO_TARGET=Desktop \
#			-DCMAKE_BUILD_TYPE=Release \
#  \
#	&& PKG_VERS=$(echo "${VERS}" | sed 's/^v//') \
#	&& checkinstall --pkgname rstudio --pkgversion "${PKG_VERS}" -y \
#  \
#  # Clean the system of packages used for building
#	&& cd /tmp \
#	&& rm -rf "rstudio-$VERS"

WORKDIR /root
